import keyMirror from 'keymirror'

export default keyMirror({
  CLOSE_MODAL: null,
  CLOSE_CONFIRM_MODAL: null,
  OPEN_MODAL: null,
  OPEN_CONFIRM_MODAL: null,
  authorizationStatusDidChange: null,
  authorizationStatusWillChange: null,
  bufferedProgressDidChange: null,
  eligibleForSubscribeView: null,
  loaded: null,
  mediaCanPlay: null,
  mediaItemDidChange: null,
  mediaItemStateDidChange: null,
  mediaItemStateWillChange: null,
  mediaItemWillChange: null,
  mediaPlaybackError: null,
  metadataDidChange: null,
  playbackBitrateDidChange: null,
  playbackDurationDidChange: null,
  playbackProgressDidChange: null,
  playbackStateDidChange: null,
  playbackStateWillChange: null,
  playbackTargetAvailableDidChange: null,
  playbackTimeDidChange: null,
  playbackVolumeDidChange: null,
  primaryPlayerDidChange: null,
  queueItemsDidChange: null,
  queuePositionDidChange: null,
  storefrontCountryCodeDidChange: null,
  storefrontIdentifierDidChange: null,
  userTokenDidChange: null
})
